"""
Migrations for UserAuthentication
Generated by Django 5.1 on 2024-11-05 05:33
"""

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migrations for UserAuthentication
    """
    dependencies = [
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True,
                                      help_text='Designates whether this user'
                                                ' should be treated as active.'
                                                ' Unselect this instead of'
                                                ' deleting accounts.',
                                      verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username'
                                                             ' already exists.'},
                                   help_text='Required. 150 characters or fewer.'
                                             ' Letters, digits and @/./+/-/_ only.',
                                   max_length=150, unique=True,
                                   validators=[django.contrib.auth.validators.
                                   UnicodeUsernameValidator()],
                                   verbose_name='username'),
        ),
    ]
